# Route for user sign in
POST http://localhost:3000/api/signin
Content-Type: application/json

{
    "email":"claude65@example.com",
    "password":"Cl@ude1958!"
}



###
# Route to destroy JWT
POST http://localhost:3000/api/logout
Cookie:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTc0MTg5MTcxMCwiZXhwIjoxNzQxOTAyNTEwfQ.W6p78rFPQifDS_eHE1m0lRi16-xCL80JAf1fUAnXLtA

###
# Route to filter events
GET http://localhost:3000/api/filter-event

###
# Route to messages
GET http://localhost:3000/api/messages?userId1=3&userId2=2
Cookie:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTc0MzYwNDg0NiwiZXhwIjoxNzQzNjE1NjQ2fQ.xJsD9xjWtAYDGPDmLX30Eqk4_Yb-v0YdP-cRf6WxSW0"

###
# Route to messages
POST http://localhost:3000/api/messages?userId=3
Content-Type: application/json
Cookie:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTc0MzYwNDg0NiwiZXhwIjoxNzQzNjE1NjQ2fQ.xJsD9xjWtAYDGPDmLX30Eqk4_Yb-v0YdP-cRf6WxSW0

{
    "sender_id": 3,
    "receiver_id": 2,
    "content": "JE TESTE MES MESSAGES"
}



###
# Route pour récupérer toutes les conversations d'un utilisateur
GET http://localhost:3000/api/conversations?userId=3
Cookie: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTc0MzcwNTc5MiwiZXhwIjoxNzQzNzE2NTkyfQ.FRL3uE6OMaLn-bAabzRPmBOdCpbhtu6h83Qz1idVlyA

###
GET http://localhost:3000/api/verify-token
Cookie:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTc0MDQ5NTg4MiwiZXhwIjoxNzQwNTA2NjgyfQ.FCv_XdXD_wi-fgfKnm9JgBraRSqWKlwpGAhorMp5eMA

###
# Route to events
GET http://localhost:3000/api/events

###
# Route to profils
GET http://localhost:3000/api/profils
Cookie: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTc0MjgyMDcwMSwiZXhwIjoxNzQyODMxNTAxfQ.gIojzo5AshB1lyeuL1mhS5CB_OZkm48H5s5shY7xCaw


###
# Route to get account details
GET http://localhost:3000/api/visitor-profile/12
Cookie:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTc0Mjg0NTEwNCwiZXhwIjoxNzQyODU1OTA0fQ.hkGZ-4swjHvQTiW7czhbRn0XZwzhfQTofjD5JA6RxRY

###
# Route to get account details
GET http://localhost:3000/api/my-account
Cookie:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTc0Mjc2OTkyMCwiZXhwIjoxNzQyNzgwNzIwfQ.kZtUf42-u-IfSGkEupi0LxrVIntcbVfy-wjaOQSTdNA


###
# Route to update account details
PATCH  http://localhost:3000/api/my-account
Content-Type: application/json
Cookie:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTc0MDUyNTEzNCwiZXhwIjoxNzQwNTM1OTM0fQ.19PQmiqti2Z163sRitfQE5Iq8BmF2V97XcXJRCS-Egw

{
    "firstname": "jean-Claude",
    "city":"LYON",
    "description": "Peintre en herbe.",
    "labels": [2, 6],
    "smoker": "false",
    "pet": "true",
    "music": "Jazz"
}

###
# Route to delete account details
DELETE  http://localhost:3000/api/my-account
Cookie:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTc0MDM4OTY2MiwiZXhwIjoxNzQwNDAwNDYyfQ.9BOd92rNDnhDZSTrDk8Kpt7phUuLnG-hKiFMDBmjX3g


### 
# Route to sign up
POST http://localhost:3000/api/signup
Content-Type: application/json

{
    "email": "newuser123@example.com", 
    "password": "NewPassword2023!",
    "repeat_password": "NewPassword2023!",  
    "firstname": "Alice", 
    "gender": "Femme", 
    "gender_match": "Homme", 
    "age": "61", 
    "height": "165",   
    "marital": "Célibataire", 
    "pet": "false",   
    "city": "TOULOUSE",
    "description": "<script>hello</script> j'aime les chats",
    "smoker": "false",
    "music": "variété française",
    "picture":"",
    "zodiac":"poisson",
    "labels": ["Nature", "Culturel"]
}

### 
# Route to get up to 4 events from a user connected
GET http://localhost:3000/api/homepage-events
Cookie: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTczOTk4NTI2MywiZXhwIjoxNzM5OTk2MDYzfQ.L4La2yQW25pF5IizrdBOwi9g-sHlSIZ-j-rGkeEccU0

### 
# Route to get up to 6 profiles from a user connected
GET http://localhost:3000/api/homepage-profiles
Cookie: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTc0Mjc2OTkyMCwiZXhwIjoxNzQyNzgwNzIwfQ.kZtUf42-u-IfSGkEupi0LxrVIntcbVfy-wjaOQSTdNA