BEGIN;
--
DROP TABLE IF EXISTS "user_event", "user_label", "event", "label", "message", "role", "user";

-- Creation of tables
CREATE TABLE "role" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "user" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "slug" VARCHAR(255) NOT NULL,
    "gender" VARCHAR(255) NOT NULL,
    "firstname" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "description" TEXT NULL,
    "age" INTEGER NOT NULL,
    "height" INTEGER NOT NULL,
    "smoker" BOOLEAN NULL,
    "marital" VARCHAR(255) NOT NULL,
    "pet" BOOLEAN NOT NULL,
    "city" VARCHAR(255) NOT NULL,
    "music" VARCHAR(255) NULL,
    "picture" VARCHAR(255) NULL,
    "zodiac" VARCHAR(255) NULL,
    "gender_match" VARCHAR(255) NOT NULL,
    "role_id" INTEGER REFERENCES "role"("id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "label" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "event" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "slug" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "date" DATE NOT NULL,
    "time" TIME NOT NULL,
    "city" VARCHAR(255) NOT NULL,
    "street" TEXT NOT NULL,
    "street_number" INTEGER NOT NULL,
    "zip_code" INTEGER NOT NULL,
    "label_id" INTEGER REFERENCES "label"("id"),
    "picture" VARCHAR(255) NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "message" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "content" TEXT NOT NULL,
    "sender_id" INTEGER REFERENCES "user"("id"),
    "receiver_id" INTEGER REFERENCES "user"("id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

-- Association table for many-to-many relationship between user and event
CREATE TABLE "user_event" (
    "user_id" INTEGER REFERENCES "user"("id"),
    "event_id" INTEGER REFERENCES "event"("id"),
    PRIMARY KEY ("user_id", "event_id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

-- Association table for many-to-many relationship between user and label
CREATE TABLE "user_label" (
    "user_id" INTEGER REFERENCES "user"("id"),
    "label_id" INTEGER REFERENCES "label"("id"),
    PRIMARY KEY ("user_id", "label_id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

COMMIT;
